components:
  securitySchemes:
    basicAuth:
      in: header
      scheme: basic
      type: http
    bearerAuth:
      bearerFormat: JWT
      in: header
      scheme: bearer
      type: http
externalDocs:
  description: Project Website
  url: https://www.ifs.tuwien.ac.at/infrastructures/dbrepo/1.13/
info:
  contact:
    email: andreas.rauber@tuwien.ac.at
    name: Prof. Andreas Rauber
  description: |
    The merged REST API of DBRepo for users, developers and data stewards to be accessed publicly. Have a look at
    the [source code](https://gitlab.phaidra.org/fair-data-austria-db-repository/fda-services) for non-public endpoints
    that are used between the services themselves.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  title: REST API
  version: 1.13.1
openapi: 3.1.0
servers:
  - description: Test Instance
    url: https://test.dbrepo.tuwien.ac.at
  - description: Local Instance
    url: http://localhost
